INSERT INTO mercadopublico_licitacion (
    codigo,
    nombre,
    descripcion,
    estado,
    codigo_comprador,
    nombre_comprador,
    rut_unidad_comprador,
    codigo_unidad_comprador,
    nombre_unidad_comprador,
    direccion_unidad_comprador,
    comuna_unidad_comprador,
    region_unidad_comprador,
    rut_usuario_comprador,
    codigo_usuario_comprador,
    nombre_usuario_comprador,
    cargo_usuario_comprador,
    codigo_tipo_licitacion,
    tipo_licitacion,
    tipo_convocatoria,
    estimacion,
    monto_estimado,
    moneda,
    modalidad,
    tiempo_duracion_contrato,
    fecha_creacion,
    fecha_cierre,
    fecha_inicio,
    fecha_final,
    fecha_proceso
)
VALUES (
    %(codigo)s,
    %(nombre)s,
    %(descripcion)s,
    %(estado)s,
    %(codigo_comprador)s,
    %(nombre_comprador)s,
    %(rut_unidad_comprador)s,
    %(codigo_unidad_comprador)s,
    %(nombre_unidad_comprador)s,
    %(direccion_unidad_comprador)s,
    %(comuna_unidad_comprador)s,
    %(region_unidad_comprador)s,
    %(rut_usuario_comprador)s,
    %(codigo_usuario_comprador)s,
    %(nombre_usuario_comprador)s,
    %(cargo_usuario_comprador)s,
    %(codigo_tipo_licitacion)s,
    %(tipo_licitacion)s,
    %(tipo_convocatoria)s,
    %(estimacion)s,
    %(monto_estimado)s,
    %(moneda)s,
    %(modalidad)s,
    %(tiempo_duracion_contrato)s,
    %(fecha_creacion)s,
    %(fecha_cierre)s,
    %(fecha_inicio)s,
    %(fecha_final)s,
    NOW()
)
ON CONFLICT (codigo) DO UPDATE SET
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    estado = EXCLUDED.estado,
    codigo_comprador = EXCLUDED.codigo_comprador,
    nombre_comprador = EXCLUDED.nombre_comprador,
    rut_unidad_comprador = EXCLUDED.rut_unidad_comprador,
    codigo_unidad_comprador = EXCLUDED.codigo_unidad_comprador,
    nombre_unidad_comprador = EXCLUDED.nombre_unidad_comprador,
    direccion_unidad_comprador = EXCLUDED.direccion_unidad_comprador,
    comuna_unidad_comprador = EXCLUDED.comuna_unidad_comprador,
    region_unidad_comprador = EXCLUDED.region_unidad_comprador,
    rut_usuario_comprador = EXCLUDED.rut_usuario_comprador,
    codigo_usuario_comprador = EXCLUDED.codigo_usuario_comprador,
    nombre_usuario_comprador = EXCLUDED.nombre_usuario_comprador,
    cargo_usuario_comprador = EXCLUDED.cargo_usuario_comprador,
    codigo_tipo_licitacion = EXCLUDED.codigo_tipo_licitacion,
    tipo_licitacion = EXCLUDED.tipo_licitacion,
    tipo_convocatoria = EXCLUDED.tipo_convocatoria,
    estimacion = EXCLUDED.estimacion,
    monto_estimado = EXCLUDED.monto_estimado,
    moneda = EXCLUDED.moneda,
    modalidad = EXCLUDED.modalidad,
    tiempo_duracion_contrato = EXCLUDED.tiempo_duracion_contrato,
    fecha_creacion = EXCLUDED.fecha_creacion,
    fecha_cierre = EXCLUDED.fecha_cierre,
    fecha_inicio = EXCLUDED.fecha_inicio,
    fecha_final = EXCLUDED.fecha_final,
    fecha_proceso = NOW()